// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnLLuH8WSpgVvMGGrMyt_rf1_OctB1yY',
    appId: '1:248024044480:web:d0a6d47c985c28306b2e25',
    messagingSenderId: '248024044480',
    projectId: 'run-together-fisayoapps-14',
    authDomain: 'run-together-fisayoapps-14.firebaseapp.com',
    storageBucket: 'run-together-fisayoapps-14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDh5KfTv7emLTU2OG7Fb07GMLyvP8t7Ls',
    appId: '1:248024044480:android:93860068ba44066d6b2e25',
    messagingSenderId: '248024044480',
    projectId: 'run-together-fisayoapps-14',
    storageBucket: 'run-together-fisayoapps-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vwvJKkI1-sRSmxkIMgiCvq1Aioqikkg',
    appId: '1:248024044480:ios:7fae66f0ed807d306b2e25',
    messagingSenderId: '248024044480',
    projectId: 'run-together-fisayoapps-14',
    storageBucket: 'run-together-fisayoapps-14.firebasestorage.app',
    iosBundleId: 'com.fisayoapps.runTogether',
  );
}
